apiVersion: v1
kind: Pod
metadata:
 name: Live
spec:
 containers:
 - image: figent/Live
   name: moringak8
   livenessProbe:
     httpGet:
       path: /
       port: 8080
     initialDelaySeconds: 20
